### ISSUE TITLE
Add `"collect": "true"` to the properties files for all collect forms

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-configurer#20]
In order for the Collect app to download forms from an instance, the collect form properties file must include `context.collect: true`. To avoid manual changes to the collect properties files, this should be done automatically by medic-configurer when converting collect forms.

**Comment by abbyad** [comment]
I think this is already done here: https://github.com/medic/medic-configurer/blob/c4ef0febd85c553b5e9f7f4526f8c0df9022a58e/src/fn/upload-collect-forms.js#L5

Is it not working anymore?

**Comment by abbyad** [comment]
I just tested on `beta-1.5.11`  and it works, but only if you **don't** have a json properties file for that form with a `context` field.

**Comment by sglangevin** [comment]
Right, so I think we need to have it working for forms that already have json properties files, which will apply to many of our projects that are upgrading to 2.13.

**Comment by alxndrsn** [comment]
I think the current behaviour is correct.

> I just tested on `beta-1.5.11`  and it works, but only if you **don't** have a json properties file for that form with a `context` field.

What are you setting in the `context` field, if you aren't setting `collect: true`?  Are there other options which might be relevant for a Collect form?

**Comment by alxndrsn** [comment]
It looks to me like all the standard forms have unnecessary `context` fields set in their properties files.  PR to remove these at https://github.com/medic/medic-projects/pull/2805.

**Comment by abbyad** [comment]
I've already removed those in the 2.13 branch that I've been working on this week as part of the Standard push.

**Comment by abbyad** [comment]
Previously we had:
```
{
	"context": {
		"person": false,
		"place": false,
		"expression": "false"
	}
}
```

and `collect:true` covers all of that

**Comment by alxndrsn** [comment]
Great 👍

**Comment by sglangevin** [comment]
Thanks guys!
