### ISSUE TITLE
Move new contact person to first page - move the group inside previous group

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-configurer#22]
Rationale: we want to show the new contact fields below the "Select Primary Contact" question, not on a separate page.

Currently done crudely at https://github.com/medic/medic-projects/blob/3f6671f79b1763d45e5faab87cea8e4b7ce5aae8/standard/forms/process_place_forms.sh#L88-L95

**Comment by alxndrsn** [comment]
@abbyad i think this achieves what you want - please have a look

**Comment by abbyad** [comment]
Yes, looking at the expected output this would achieve what we need. Thanks!

**Comment by alxndrsn** [comment]
Released as `1.6.0`.
